services:
  frontend:
    build:
      context: ./frontend
      target: production
      args: 
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3100:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=America/Campo_Grande
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3101:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=America/Campo_Grande
      - PGTZ=America/Campo_Grande
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "3102:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Campo_Grande
      PGTZ: America/Campo_Grande
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "3103:9000" # API do MinIO
      - "3104:9001" # Console do MinIO
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      TZ: America/Campo_Grande
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    restart: unless-stopped

volumes:
  pgdata:
  miniodata: